### ISSUE TITLE
CursorAdapter实现

### ISSUE THREAD

**Issue by Chen-Sir** [Frank-Zhu/AndroidRecyclerViewDemo#1]
你好，你能详细说下 BaseAbstractRecycleCursorAdapter 这个类 的逻辑吗？

**Comment by Frank-Zhu** [comment]
@Chen-Sir 不好意思，之前没看到这个issue，有什么看不懂吗？和listView的cursor实现是类似的，就是加了两个观察者监听数据库数据变化.

**Comment by Chen-Sir** [comment]
@Frank-Zhu 没事，这两天看了下 看懂了  谢谢    主要是之前没用过CursorAdapter   我是个新手

**Comment by Frank-Zhu** [comment]
@Chen-Sir OK,看懂了就好。
