### ISSUE TITLE
我想知道StaggeredGridLayoutManager瀑布流的如何加header并设置占据整行空间呢？

### ISSUE THREAD

**Issue by bajian** [Frank-Zhu/AndroidRecyclerViewDemo#4]
您的文章里提及了LinearLayoutManager和GridLayoutManager的设置方法，让我获益匪浅
我照着写可以设置header但是没法设置占据整行空间。
看了下GridLayoutManager的是这样实现的：
`if (gridLayoutManager != null) {//设置头部及底部View占据整行空间
            gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    return (mAdapter.isHeaderView(position) || mAdapter.isBottomView(position)) ? gridLayoutManager.getSpanCount() : 1;
                }
            });
        }`
那StaggeredGridLayoutManager要怎么设置header宽度呢？

**Comment by bajian** [comment]
已经解决了。onBindViewHolder对底部和头部的view设置LP的属性：layoutParams.setFullSpan(true);

例如：

```
@Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (holder instanceof HeaderViewHolder) {
            LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
            ((HeaderViewHolder) holder).mLlHeader.setLayoutParams(params);

            //设置占满全格
            StaggeredGridLayoutManager.LayoutParams layoutParams = new StaggeredGridLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            layoutParams.setFullSpan(true);
            holder.itemView.setLayoutParams(layoutParams);
        } else if (holder instanceof ViewHolder) {
            onMyContentBindViewHolder((ViewHolder)holder, position-mHeaderCount-mBottomCount);
        }
    }
```

**Comment by Frank-Zhu** [comment]
@bajian 这个在ViewHolder 的构造函数里面设置比在绑定数据的时候设置更合理一些，你觉得呢？

**Comment by bajian** [comment]
@Frank-Zhu 恩，这样就不会每次加载数据都重新设置了，高效不少..试了下没什么问题。
