### ISSUE TITLE
recyclerview如何控制他的某个item不被销毁

### ISSUE THREAD

**Issue by fflamingogo** [Frank-Zhu/AndroidRecyclerViewDemo#5]
我的item中，有个viewpager翻到了其他页数，recyclerview滑到底部，viewpager老是重新初始化到了第一页，应该怎么让他不被销毁

**Comment by Frank-Zhu** [comment]
@fflamingogo 你可以记录一下你的viewpager滑动到第几页，在重新绑定数据的时候再设置回去就可以了。

**Comment by fflamingogo** [comment]
@Frank-Zhu 看来只能这样了，谢谢
