### ISSUE TITLE
新问题

### ISSUE THREAD

**Issue by damingwangguan** [Frank-Zhu/AndroidRecyclerViewDemo#9]
在recycleview 与scrollview嵌套的使用中，在您的例子最后一个的情况，如果是textview在recycleview上面，那么在打开的时候会出现recycleiview自动滚到第一栏，这个问题一直不知道怎么解决，不知道是否有空看一下

**Comment by Frank-Zhu** [comment]
@damingwangguan  你layoutManager用的哪个？升级一下support包，官方已经支持嵌套了，你可以再试试！
